set_property IOSTANDARD LVCMOS33 [get_ports *]
set_property PACKAGE_PIN P5 [get_ports {note_in[7]}]
set_property PACKAGE_PIN P4 [get_ports {note_in[6]}]
set_property PACKAGE_PIN P3 [get_ports {note_in[5]}]
set_property PACKAGE_PIN P2 [get_ports {note_in[4]}]
set_property PACKAGE_PIN R2 [get_ports {note_in[3]}]
set_property PACKAGE_PIN M4 [get_ports {note_in[2]}]
set_property PACKAGE_PIN N4 [get_ports {note_in[1]}]
set_property PACKAGE_PIN R1 [get_ports {note_in[0]}]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN U4 [get_ports higher]
set_property PACKAGE_PIN R17 [get_ports lower]
set_property PACKAGE_PIN P15 [get_ports rst_n]
set_property PACKAGE_PIN H17 [get_ports speaker]
set_property PACKAGE_PIN F6 [get_ports {led_out[7]}]
set_property PACKAGE_PIN G4 [get_ports {led_out[6]}]
set_property PACKAGE_PIN G3 [get_ports {led_out[5]}]
set_property PACKAGE_PIN J4 [get_ports {led_out[4]}]
set_property PACKAGE_PIN H4 [get_ports {led_out[3]}]
set_property PACKAGE_PIN J3 [get_ports {led_out[2]}]
set_property PACKAGE_PIN J2 [get_ports {led_out[1]}]
set_property PACKAGE_PIN K2 [get_ports {led_out[0]}]
set_property PACKAGE_PIN G2  [get_ports {sel[7]}]
set_property PACKAGE_PIN C2 [get_ports {sel[6]}]
set_property PACKAGE_PIN C1 [get_ports {sel[5]}]
set_property PACKAGE_PIN H1 [get_ports {sel[4]}]
set_property PACKAGE_PIN G1 [get_ports {sel[3]}]
set_property PACKAGE_PIN F1 [get_ports {sel[2]}]
set_property PACKAGE_PIN E1 [get_ports {sel[1]}]
set_property PACKAGE_PIN G6 [get_ports {sel[0]}]
set_property PACKAGE_PIN D4 [get_ports {seg_2[7]}]
set_property PACKAGE_PIN E3 [get_ports {seg_2[6]}]
set_property PACKAGE_PIN D3 [get_ports {seg_2[5]}]
set_property PACKAGE_PIN F4 [get_ports {seg_2[4]}]
set_property PACKAGE_PIN F3 [get_ports {seg_2[3]}]
set_property PACKAGE_PIN E2 [get_ports {seg_2[2]}]
set_property PACKAGE_PIN D2 [get_ports {seg_2[1]}]
set_property PACKAGE_PIN H2 [get_ports {seg_2[0]}]
set_property PACKAGE_PIN B4 [get_ports {seg[7]}]
set_property PACKAGE_PIN A4 [get_ports {seg[6]}]
set_property PACKAGE_PIN A3 [get_ports {seg[5]}]
set_property PACKAGE_PIN B1 [get_ports {seg[4]}]
set_property PACKAGE_PIN A1 [get_ports {seg[3]}]
set_property PACKAGE_PIN B3 [get_ports {seg[2]}]
set_property PACKAGE_PIN B2 [get_ports {seg[1]}]
set_property PACKAGE_PIN D5 [get_ports {seg[0]}]






