set_property IOSTANDARD LVCMOS33 [get_ports *]

set_property PACKAGE_PIN P5 [get_ports {note_in[7]}]
set_property PACKAGE_PIN P4 [get_ports {note_in[6]}]
set_property PACKAGE_PIN P3 [get_ports {note_in[5]}]
set_property PACKAGE_PIN P2 [get_ports {note_in[4]}]
set_property PACKAGE_PIN R2 [get_ports {note_in[3]}]
set_property PACKAGE_PIN M4 [get_ports {note_in[2]}]
set_property PACKAGE_PIN N4 [get_ports {note_in[1]}]
set_property PACKAGE_PIN U3 [get_ports {note_in[0]}]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN U4 [get_ports higher]
set_property PACKAGE_PIN R17 [get_ports lower]
set_property PACKAGE_PIN P15 [get_ports rst_n]
set_property PACKAGE_PIN H17 [get_ports speaker]
set_property PACKAGE_PIN F6 [get_ports {led_out[7]}]
set_property PACKAGE_PIN G4 [get_ports {led_out[6]}]
set_property PACKAGE_PIN G3 [get_ports {led_out[5]}]
set_property PACKAGE_PIN J4 [get_ports {led_out[4]}]
set_property PACKAGE_PIN H4 [get_ports {led_out[3]}]
set_property PACKAGE_PIN J3 [get_ports {led_out[2]}]
set_property PACKAGE_PIN J2 [get_ports {led_out[1]}]
set_property PACKAGE_PIN K2 [get_ports {led_out[0]}]

set_property PACKAGE_PIN R1 [get_ports adjust]
set_property PACKAGE_PIN T5 [get_ports commit]
set_property PACKAGE_PIN K3 [get_ports commit_out]

