# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Wells/Desktop/Major CS/Digital Logic/Mini/Mini_Piano.srcs/sources_1/ip/rom_pic1/rom_pic1.xci
# IP: The module: 'rom_pic1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Wells/Desktop/Major CS/Digital Logic/Mini/Mini_Piano.srcs/sources_1/ip/rom_pic1/rom_pic1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_pic1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Wells/Desktop/Major CS/Digital Logic/Mini/Mini_Piano.srcs/sources_1/ip/rom_pic1/rom_pic1.xci
# IP: The module: 'rom_pic1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Wells/Desktop/Major CS/Digital Logic/Mini/Mini_Piano.srcs/sources_1/ip/rom_pic1/rom_pic1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_pic1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
